---
title: Ciptamedia.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
encoding: utf-8
markdown: kramdown
baseurl: "/ciptamedia.github.io"
permalink: "/:categories/:title.html"
